services:
  
  nginx:
    container_name: web-server
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web-content:/usr/share/nginx/html:ro

  browsersync:
    container_name: browser-sync
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./web-content:/app
      - ./browsersync:/app/config
      - ./browsersync/package.json:/app/package.json
    command: sh ./config/start.sh
    depends_on:
      - nginx
